function hardware_joint_names = getHardwareJointNames(r)
%NOTEST


hardware_joint_names = {...
      'torsoYaw', ...
      'torsoPitch', ...
      'torsoRoll', ...
      'lowerNeckPitch', ...
      'neckYaw', ...
      'upperNeckPitch', ...
      'rightShoulderPitch', ...
      'rightShoulderRoll', ...
      'rightShoulderYaw', ...
      'rightElbowPitch', ...
      'rightForearmYaw', ...
      'rightWristRoll', ...
      'rightWristPitch', ...
      'leftShoulderPitch', ...
      'leftShoulderRoll', ...
      'leftShoulderYaw', ...
      'leftElbowPitch', ...
      'leftForearmYaw', ...
      'leftWristRoll', ...
      'leftWristPitch', ...
      'rightHipYaw', ...
      'rightHipRoll', ...
      'rightHipPitch', ...
      'rightKneePitch', ...
      'rightAnklePitch', ...
      'rightAnkleRoll', ...
      'leftHipYaw', ...
      'leftHipRoll', ...
      'leftHipPitch', ...
      'leftKneePitch', ...
      'leftAnklePitch', ...
      'leftAnkleRoll'};
